apiVersion: v1
kind: Pod
metadata:
  name: ci-policy-compliant
  labels:
    app: ci-test
    environment: test
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: nginx
      image: 495278513365.dkr.ecr.ap-south-1.amazonaws.com/k8s-policy-demo:1.27
      securityContext:
        privileged: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
